/* Melange Tattoo — gallery data.
   Newest first. To add a photo: put <id>-480.webp and <id>-1080.webp in assets/work/
   and add a line at the top. cat is one of: dragon, snake, koi, animal, floral, pattern, character, more. */
window.MELANGE_GALLERY = [
  {"id": "custom-117", "cat": "animal", "w": 1501, "h": 2000, "en": "Phoenix tattoo in red ink on the forearm, by Melange", "ko": "봉황 타투, 붉은 잉크 · 팔뚝 · 멜란지 작업", "placeEn": "Forearm", "placeKo": "팔뚝"},
  {"id": "custom-115", "cat": "floral", "w": 1501, "h": 2000, "en": "Flower tattoo in blue ink on the shoulder, by Melange", "ko": "꽃 타투, 푸른 잉크 · 어깨 · 멜란지 작업", "placeEn": "Shoulder", "placeKo": "어깨"},
  {"id": "custom-116", "cat": "pattern", "w": 1501, "h": 2000, "en": "Pattern tattoo in blue ink on the forearm, by Melange", "ko": "패턴 타투, 푸른 잉크 · 팔뚝 · 멜란지 작업", "placeEn": "Forearm", "placeKo": "팔뚝"},
  {"id": "custom-109", "cat": "character", "w": 1600, "h": 2000, "en": "Stitch, blue ink character tattoo", "ko": "스티치, 푸른 잉크 캐릭터 타투", "placeEn": "", "placeKo": ""},
  {"id": "custom-110", "cat": "character", "w": 1501, "h": 2000, "en": "Blastoise, blue ink character tattoo", "ko": "거북왕, 푸른 잉크 캐릭터 타투", "placeEn": "", "placeKo": ""},
  {"id": "custom-111", "cat": "character", "w": 1602, "h": 2000, "en": "Oshawott, blue ink character tattoo", "ko": "수댕이, 푸른 잉크 캐릭터 타투", "placeEn": "", "placeKo": ""},
  {"id": "custom-112", "cat": "character", "w": 1501, "h": 2000, "en": "Boba Fett, blue ink character tattoo on the forearm", "ko": "보바 펫, 푸른 잉크 캐릭터 타투 (팔뚝)", "placeEn": "Forearm", "placeKo": "팔뚝"},
  {"id": "custom-113", "cat": "character", "w": 1501, "h": 2000, "en": "Vaporeon, blue ink character tattoo", "ko": "샤미드, 푸른 잉크 캐릭터 타투", "placeEn": "", "placeKo": ""},
  {"id": "custom-114", "cat": "character", "w": 1500, "h": 2000, "en": "Kyogre, blue ink character tattoo on the forearm", "ko": "가이오가, 푸른 잉크 캐릭터 타투 (팔뚝)", "placeEn": "Forearm", "placeKo": "팔뚝"},
  {"id": "dragon-01", "cat": "character", "w": 1600, "h": 2131, "en": "Gyarados, blue ink character tattoo on the upper arm", "ko": "갸라도스, 푸른 잉크 캐릭터 타투 (팔 위쪽)", "placeEn": "Upper arm", "placeKo": "팔 위쪽"},
  {"id": "snake-01", "cat": "snake", "w": 1600, "h": 2131, "en": "Snake tattoo in blue ink on the forearm, by Melange", "ko": "뱀 타투, 푸른 잉크 · 팔뚝 · 멜란지 작업", "placeEn": "Forearm", "placeKo": "팔뚝"},
  {"id": "phoenix-01", "cat": "character", "w": 1600, "h": 2131, "en": "Ho-Oh & Suicune, blue ink character tattoo on the forearm", "ko": "칠색조 & 스이쿤, 푸른 잉크 캐릭터 타투 (팔뚝)", "placeEn": "Forearm", "placeKo": "팔뚝"},
  {"id": "flowers-01", "cat": "floral", "w": 1600, "h": 2131, "en": "Flower tattoo in blue ink on the forearm, by Melange", "ko": "꽃 타투, 푸른 잉크 · 팔뚝 · 멜란지 작업", "placeEn": "Forearm", "placeKo": "팔뚝"},
  {"id": "clouds-01", "cat": "pattern", "w": 1600, "h": 2131, "en": "Pattern tattoo in blue ink on the thigh, by Melange", "ko": "패턴 타투, 푸른 잉크 · 허벅지 · 멜란지 작업", "placeEn": "Thigh", "placeKo": "허벅지"},
  {"id": "lightning-01", "cat": "dragon", "w": 1600, "h": 2131, "en": "Dragon tattoo in blue ink on the ribs, by Melange", "ko": "용 타투, 푸른 잉크 · 옆구리 · 멜란지 작업", "placeEn": "Ribs", "placeKo": "옆구리"},
  {"id": "pattern-01", "cat": "pattern", "w": 1600, "h": 2131, "en": "Pattern tattoo in blue ink on the forearm, by Melange", "ko": "패턴 타투, 푸른 잉크 · 팔뚝 · 멜란지 작업", "placeEn": "Forearm", "placeKo": "팔뚝"},
  {"id": "dragon-02", "cat": "dragon", "w": 1600, "h": 2131, "en": "Dragon tattoo in blue ink on the shoulder, by Melange", "ko": "용 타투, 푸른 잉크 · 어깨 · 멜란지 작업", "placeEn": "Shoulder", "placeKo": "어깨"},
  {"id": "phoenix-02", "cat": "animal", "w": 1600, "h": 2131, "en": "Animal tattoo in blue ink on the both arms, by Melange", "ko": "동물 타투, 푸른 잉크 · 양팔 · 멜란지 작업", "placeEn": "Both arms", "placeKo": "양팔"},
  {"id": "pattern-02", "cat": "floral", "w": 1600, "h": 2131, "en": "Flower tattoo in blue ink on the full arm, by Melange", "ko": "꽃 타투, 푸른 잉크 · 팔 전체 · 멜란지 작업", "placeEn": "Full arm", "placeKo": "팔 전체"},
  {"id": "pattern-03", "cat": "pattern", "w": 1600, "h": 2131, "en": "Pattern tattoo in blue ink on the upper arm, by Melange", "ko": "패턴 타투, 푸른 잉크 · 팔 위쪽 · 멜란지 작업", "placeEn": "Upper arm", "placeKo": "팔 위쪽"},
  {"id": "custom-001", "cat": "dragon", "w": 1501, "h": 2000, "en": "Dragon tattoo in blue ink on the upper arm, by Melange", "ko": "용 타투, 푸른 잉크 · 팔 위쪽 · 멜란지 작업", "placeEn": "Upper arm", "placeKo": "팔 위쪽"},
  {"id": "custom-002", "cat": "more", "w": 1501, "h": 2000, "en": "Custom tattoo in blue ink, by Melange", "ko": "커스텀 타투, 푸른 잉크 · 멜란지 작업", "placeEn": "", "placeKo": ""},
  {"id": "custom-003", "cat": "more", "w": 1602, "h": 2000, "en": "Custom tattoo in blue ink on the forearm, by Melange", "ko": "커스텀 타투, 푸른 잉크 · 팔뚝 · 멜란지 작업", "placeEn": "Forearm", "placeKo": "팔뚝"},
  {"id": "custom-004", "cat": "dragon", "w": 1501, "h": 2000, "en": "Dragon tattoo in blue ink on the forearm, by Melange", "ko": "용 타투, 푸른 잉크 · 팔뚝 · 멜란지 작업", "placeEn": "Forearm", "placeKo": "팔뚝"},
  {"id": "custom-005", "cat": "more", "w": 1501, "h": 2000, "en": "Custom tattoo in blue ink on the upper arm, by Melange", "ko": "커스텀 타투, 푸른 잉크 · 팔 위쪽 · 멜란지 작업", "placeEn": "Upper arm", "placeKo": "팔 위쪽"},
  {"id": "custom-006", "cat": "pattern", "w": 1501, "h": 2000, "en": "Pattern tattoo in blue ink on the forearm, by Melange", "ko": "패턴 타투, 푸른 잉크 · 팔뚝 · 멜란지 작업", "placeEn": "Forearm", "placeKo": "팔뚝"},
  {"id": "custom-007", "cat": "floral", "w": 1600, "h": 2000, "en": "Flower tattoo in blue ink on the forearm, by Melange", "ko": "꽃 타투, 푸른 잉크 · 팔뚝 · 멜란지 작업", "placeEn": "Forearm", "placeKo": "팔뚝"},
  {"id": "custom-008", "cat": "more", "w": 1125, "h": 2000, "en": "Custom tattoo in blue ink on the forearm, by Melange", "ko": "커스텀 타투, 푸른 잉크 · 팔뚝 · 멜란지 작업", "placeEn": "Forearm", "placeKo": "팔뚝"},
  {"id": "custom-009", "cat": "character", "w": 1501, "h": 2000, "en": "Pokémon, blue ink character tattoo on the forearm", "ko": "포켓몬, 푸른 잉크 캐릭터 타투 (팔뚝)", "placeEn": "Forearm", "placeKo": "팔뚝"},
  {"id": "custom-010", "cat": "pattern", "w": 1501, "h": 2000, "en": "Pattern tattoo in blue ink on the leg, by Melange", "ko": "패턴 타투, 푸른 잉크 · 다리 · 멜란지 작업", "placeEn": "Leg", "placeKo": "다리"},
  {"id": "custom-011", "cat": "more", "w": 1600, "h": 2000, "en": "Custom tattoo in blue ink on the upper arm, by Melange", "ko": "커스텀 타투, 푸른 잉크 · 팔 위쪽 · 멜란지 작업", "placeEn": "Upper arm", "placeKo": "팔 위쪽"},
  {"id": "custom-012", "cat": "pattern", "w": 1501, "h": 2000, "en": "Pattern tattoo in blue ink on the back, by Melange", "ko": "패턴 타투, 푸른 잉크 · 등 · 멜란지 작업", "placeEn": "Back", "placeKo": "등"},
  {"id": "custom-013", "cat": "pattern", "w": 1602, "h": 2000, "en": "Pattern tattoo in blue ink on the leg, by Melange", "ko": "패턴 타투, 푸른 잉크 · 다리 · 멜란지 작업", "placeEn": "Leg", "placeKo": "다리"},
  {"id": "custom-014", "cat": "dragon", "w": 1501, "h": 2000, "en": "Dragon tattoo in blue ink on the full arm, by Melange", "ko": "용 타투, 푸른 잉크 · 팔 전체 · 멜란지 작업", "placeEn": "Full arm", "placeKo": "팔 전체"},
  {"id": "custom-015", "cat": "more", "w": 1501, "h": 2000, "en": "Custom tattoo in blue ink on the forearm, by Melange", "ko": "커스텀 타투, 푸른 잉크 · 팔뚝 · 멜란지 작업", "placeEn": "Forearm", "placeKo": "팔뚝"},
  {"id": "custom-016", "cat": "pattern", "w": 1501, "h": 2000, "en": "Pattern tattoo in blue ink on the forearm, by Melange", "ko": "패턴 타투, 푸른 잉크 · 팔뚝 · 멜란지 작업", "placeEn": "Forearm", "placeKo": "팔뚝"},
  {"id": "custom-017", "cat": "floral", "w": 1501, "h": 2000, "en": "Flower tattoo in blue ink on the upper arm, by Melange", "ko": "꽃 타투, 푸른 잉크 · 팔 위쪽 · 멜란지 작업", "placeEn": "Upper arm", "placeKo": "팔 위쪽"},
  {"id": "custom-018", "cat": "pattern", "w": 1501, "h": 2000, "en": "Pattern tattoo in blue ink on the full arm, by Melange", "ko": "패턴 타투, 푸른 잉크 · 팔 전체 · 멜란지 작업", "placeEn": "Full arm", "placeKo": "팔 전체"},
  {"id": "custom-019", "cat": "pattern", "w": 1600, "h": 2000, "en": "Pattern tattoo in blue ink on the neck, by Melange", "ko": "패턴 타투, 푸른 잉크 · 목 · 멜란지 작업", "placeEn": "Neck", "placeKo": "목"},
  {"id": "custom-020", "cat": "pattern", "w": 1600, "h": 2000, "en": "Pattern tattoo in blue ink on the upper arm, by Melange", "ko": "패턴 타투, 푸른 잉크 · 팔 위쪽 · 멜란지 작업", "placeEn": "Upper arm", "placeKo": "팔 위쪽"},
  {"id": "custom-021", "cat": "dragon", "w": 1125, "h": 2000, "en": "Dragon tattoo in blue ink on the forearm, by Melange", "ko": "용 타투, 푸른 잉크 · 팔뚝 · 멜란지 작업", "placeEn": "Forearm", "placeKo": "팔뚝"},
  {"id": "custom-022", "cat": "dragon", "w": 1333, "h": 2000, "en": "Dragon tattoo in blue ink on the full arm, by Melange", "ko": "용 타투, 푸른 잉크 · 팔 전체 · 멜란지 작업", "placeEn": "Full arm", "placeKo": "팔 전체"},
  {"id": "custom-023", "cat": "floral", "w": 1600, "h": 2000, "en": "Flower tattoo in blue ink on the collarbone, by Melange", "ko": "꽃 타투, 푸른 잉크 · 쇄골 · 멜란지 작업", "placeEn": "Collarbone", "placeKo": "쇄골"},
  {"id": "custom-024", "cat": "pattern", "w": 2000, "h": 1333, "en": "Pattern tattoo in blue ink on the chest, by Melange", "ko": "패턴 타투, 푸른 잉크 · 가슴 · 멜란지 작업", "placeEn": "Chest", "placeKo": "가슴"},
  {"id": "custom-025", "cat": "pattern", "w": 1600, "h": 2000, "en": "Pattern tattoo in blue ink on the upper arm, by Melange", "ko": "패턴 타투, 푸른 잉크 · 팔 위쪽 · 멜란지 작업", "placeEn": "Upper arm", "placeKo": "팔 위쪽"},
  {"id": "custom-026", "cat": "animal", "w": 1600, "h": 2000, "en": "Animal tattoo in blue ink on the forearm, by Melange", "ko": "동물 타투, 푸른 잉크 · 팔뚝 · 멜란지 작업", "placeEn": "Forearm", "placeKo": "팔뚝"},
  {"id": "custom-027", "cat": "dragon", "w": 1333, "h": 2000, "en": "Dragon tattoo in blue ink on the full arm, by Melange", "ko": "용 타투, 푸른 잉크 · 팔 전체 · 멜란지 작업", "placeEn": "Full arm", "placeKo": "팔 전체"},
  {"id": "custom-028", "cat": "dragon", "w": 1602, "h": 2000, "en": "Dragon tattoo in blue ink on the shoulder, by Melange", "ko": "용 타투, 푸른 잉크 · 어깨 · 멜란지 작업", "placeEn": "Shoulder", "placeKo": "어깨"},
  {"id": "custom-029", "cat": "pattern", "w": 1602, "h": 2000, "en": "Pattern tattoo in blue ink on the forearm, by Melange", "ko": "패턴 타투, 푸른 잉크 · 팔뚝 · 멜란지 작업", "placeEn": "Forearm", "placeKo": "팔뚝"},
  {"id": "custom-030", "cat": "floral", "w": 1501, "h": 2000, "en": "Flower tattoo in blue ink on the neck, by Melange", "ko": "꽃 타투, 푸른 잉크 · 목 · 멜란지 작업", "placeEn": "Neck", "placeKo": "목"},
  {"id": "custom-031", "cat": "floral", "w": 1600, "h": 2000, "en": "Flower tattoo in blue ink on the leg, by Melange", "ko": "꽃 타투, 푸른 잉크 · 다리 · 멜란지 작업", "placeEn": "Leg", "placeKo": "다리"},
  {"id": "custom-032", "cat": "pattern", "w": 1600, "h": 2000, "en": "Pattern tattoo in blue ink, by Melange", "ko": "패턴 타투, 푸른 잉크 · 멜란지 작업", "placeEn": "", "placeKo": ""},
  {"id": "custom-033", "cat": "more", "w": 1501, "h": 2000, "en": "Custom tattoo in blue ink on the back, by Melange", "ko": "커스텀 타투, 푸른 잉크 · 등 · 멜란지 작업", "placeEn": "Back", "placeKo": "등"},
  {"id": "custom-034", "cat": "dragon", "w": 2000, "h": 1333, "en": "Dragon tattoo in blue ink on the collarbone, by Melange", "ko": "용 타투, 푸른 잉크 · 쇄골 · 멜란지 작업", "placeEn": "Collarbone", "placeKo": "쇄골"},
  {"id": "custom-035", "cat": "animal", "w": 1600, "h": 2000, "en": "Animal tattoo in blue ink on the upper arm, by Melange", "ko": "동물 타투, 푸른 잉크 · 팔 위쪽 · 멜란지 작업", "placeEn": "Upper arm", "placeKo": "팔 위쪽"},
  {"id": "custom-036", "cat": "dragon", "w": 1600, "h": 2000, "en": "Dragon tattoo in blue ink on the collarbone, by Melange", "ko": "용 타투, 푸른 잉크 · 쇄골 · 멜란지 작업", "placeEn": "Collarbone", "placeKo": "쇄골"},
  {"id": "custom-037", "cat": "koi", "w": 1501, "h": 2000, "en": "Koi tattoo in blue ink on the forearm, by Melange", "ko": "잉어 타투, 푸른 잉크 · 팔뚝 · 멜란지 작업", "placeEn": "Forearm", "placeKo": "팔뚝"},
  {"id": "custom-038", "cat": "floral", "w": 1500, "h": 2000, "en": "Flower tattoo in blue ink on the full arm, by Melange", "ko": "꽃 타투, 푸른 잉크 · 팔 전체 · 멜란지 작업", "placeEn": "Full arm", "placeKo": "팔 전체"},
  {"id": "custom-039", "cat": "floral", "w": 1600, "h": 2000, "en": "Flower tattoo in blue ink on the forearm, by Melange", "ko": "꽃 타투, 푸른 잉크 · 팔뚝 · 멜란지 작업", "placeEn": "Forearm", "placeKo": "팔뚝"},
  {"id": "custom-040", "cat": "floral", "w": 1602, "h": 2000, "en": "Flower tattoo in blue ink on the ribs, by Melange", "ko": "꽃 타투, 푸른 잉크 · 옆구리 · 멜란지 작업", "placeEn": "Ribs", "placeKo": "옆구리"},
  {"id": "custom-041", "cat": "character", "w": 1501, "h": 2000, "en": "Vaporeon, blue ink character tattoo on the leg", "ko": "샤미드, 푸른 잉크 캐릭터 타투 (다리)", "placeEn": "Leg", "placeKo": "다리"},
  {"id": "custom-042", "cat": "animal", "w": 1602, "h": 2000, "en": "Animal tattoo in blue ink on the shoulder, by Melange", "ko": "동물 타투, 푸른 잉크 · 어깨 · 멜란지 작업", "placeEn": "Shoulder", "placeKo": "어깨"},
  {"id": "custom-043", "cat": "pattern", "w": 1602, "h": 2000, "en": "Pattern tattoo in blue ink on the upper arm, by Melange", "ko": "패턴 타투, 푸른 잉크 · 팔 위쪽 · 멜란지 작업", "placeEn": "Upper arm", "placeKo": "팔 위쪽"},
  {"id": "custom-044", "cat": "floral", "w": 1600, "h": 2000, "en": "Flower tattoo in blue ink on the upper arm, by Melange", "ko": "꽃 타투, 푸른 잉크 · 팔 위쪽 · 멜란지 작업", "placeEn": "Upper arm", "placeKo": "팔 위쪽"},
  {"id": "custom-045", "cat": "pattern", "w": 1602, "h": 2000, "en": "Pattern tattoo in blue ink on the forearm, by Melange", "ko": "패턴 타투, 푸른 잉크 · 팔뚝 · 멜란지 작업", "placeEn": "Forearm", "placeKo": "팔뚝"},
  {"id": "custom-046", "cat": "pattern", "w": 1501, "h": 2000, "en": "Pattern tattoo in blue ink on the hand, by Melange", "ko": "패턴 타투, 푸른 잉크 · 손 · 멜란지 작업", "placeEn": "Hand", "placeKo": "손"},
  {"id": "custom-047", "cat": "floral", "w": 1602, "h": 2000, "en": "Flower tattoo in blue ink on the upper arm, by Melange", "ko": "꽃 타투, 푸른 잉크 · 팔 위쪽 · 멜란지 작업", "placeEn": "Upper arm", "placeKo": "팔 위쪽"},
  {"id": "custom-048", "cat": "dragon", "w": 1602, "h": 2000, "en": "Dragon tattoo in blue ink on the upper arm, by Melange", "ko": "용 타투, 푸른 잉크 · 팔 위쪽 · 멜란지 작업", "placeEn": "Upper arm", "placeKo": "팔 위쪽"},
  {"id": "custom-049", "cat": "dragon", "w": 1501, "h": 2000, "en": "Dragon tattoo in blue ink on the forearm, by Melange", "ko": "용 타투, 푸른 잉크 · 팔뚝 · 멜란지 작업", "placeEn": "Forearm", "placeKo": "팔뚝"},
  {"id": "custom-050", "cat": "dragon", "w": 1602, "h": 2000, "en": "Dragon tattoo in blue ink on the forearm, by Melange", "ko": "용 타투, 푸른 잉크 · 팔뚝 · 멜란지 작업", "placeEn": "Forearm", "placeKo": "팔뚝"},
  {"id": "custom-051", "cat": "pattern", "w": 1501, "h": 2000, "en": "Pattern tattoo in blue ink on the leg, by Melange", "ko": "패턴 타투, 푸른 잉크 · 다리 · 멜란지 작업", "placeEn": "Leg", "placeKo": "다리"},
  {"id": "custom-052", "cat": "animal", "w": 1602, "h": 2000, "en": "Animal tattoo in blue ink on the forearm, by Melange", "ko": "동물 타투, 푸른 잉크 · 팔뚝 · 멜란지 작업", "placeEn": "Forearm", "placeKo": "팔뚝"},
  {"id": "custom-053", "cat": "dragon", "w": 1602, "h": 2000, "en": "Dragon tattoo in blue ink on the thigh, by Melange", "ko": "용 타투, 푸른 잉크 · 허벅지 · 멜란지 작업", "placeEn": "Thigh", "placeKo": "허벅지"},
  {"id": "custom-054", "cat": "floral", "w": 1125, "h": 2000, "en": "Flower tattoo in blue ink on the upper arm, by Melange", "ko": "꽃 타투, 푸른 잉크 · 팔 위쪽 · 멜란지 작업", "placeEn": "Upper arm", "placeKo": "팔 위쪽"},
  {"id": "custom-055", "cat": "floral", "w": 1602, "h": 2000, "en": "Flower tattoo in blue ink on the forearm, by Melange", "ko": "꽃 타투, 푸른 잉크 · 팔뚝 · 멜란지 작업", "placeEn": "Forearm", "placeKo": "팔뚝"},
  {"id": "custom-056", "cat": "character", "w": 1501, "h": 2000, "en": "Artorias, blue ink character tattoo on the leg", "ko": "아르토리우스, 푸른 잉크 캐릭터 타투 (다리)", "placeEn": "Leg", "placeKo": "다리"},
  {"id": "custom-057", "cat": "dragon", "w": 1602, "h": 2000, "en": "Dragon tattoo in blue ink on the upper arm, by Melange", "ko": "용 타투, 푸른 잉크 · 팔 위쪽 · 멜란지 작업", "placeEn": "Upper arm", "placeKo": "팔 위쪽"},
  {"id": "custom-058", "cat": "pattern", "w": 1600, "h": 2000, "en": "Pattern tattoo in blue ink on the forearm, by Melange", "ko": "패턴 타투, 푸른 잉크 · 팔뚝 · 멜란지 작업", "placeEn": "Forearm", "placeKo": "팔뚝"},
  {"id": "custom-059", "cat": "character", "w": 1600, "h": 2000, "en": "Blue cat, blue ink character tattoo on the upper arm", "ko": "파란 고양이, 푸른 잉크 캐릭터 타투 (팔 위쪽)", "placeEn": "Upper arm", "placeKo": "팔 위쪽"},
  {"id": "custom-060", "cat": "more", "w": 1501, "h": 2000, "en": "Custom tattoo in blue ink on the forearm, by Melange", "ko": "커스텀 타투, 푸른 잉크 · 팔뚝 · 멜란지 작업", "placeEn": "Forearm", "placeKo": "팔뚝"},
  {"id": "custom-061", "cat": "koi", "w": 1125, "h": 2000, "en": "Koi tattoo in blue ink on the forearm, by Melange", "ko": "잉어 타투, 푸른 잉크 · 팔뚝 · 멜란지 작업", "placeEn": "Forearm", "placeKo": "팔뚝"},
  {"id": "custom-062", "cat": "dragon", "w": 1602, "h": 2000, "en": "Dragon tattoo in blue ink on the forearm, by Melange", "ko": "용 타투, 푸른 잉크 · 팔뚝 · 멜란지 작업", "placeEn": "Forearm", "placeKo": "팔뚝"},
  {"id": "custom-063", "cat": "floral", "w": 1602, "h": 2000, "en": "Flower tattoo in blue ink on the upper arm, by Melange", "ko": "꽃 타투, 푸른 잉크 · 팔 위쪽 · 멜란지 작업", "placeEn": "Upper arm", "placeKo": "팔 위쪽"},
  {"id": "custom-064", "cat": "snake", "w": 1429, "h": 2000, "en": "Snake tattoo in blue ink on the forearm, by Melange", "ko": "뱀 타투, 푸른 잉크 · 팔뚝 · 멜란지 작업", "placeEn": "Forearm", "placeKo": "팔뚝"},
  {"id": "custom-065", "cat": "animal", "w": 1501, "h": 2000, "en": "Animal tattoo in blue ink on the upper arm, by Melange", "ko": "동물 타투, 푸른 잉크 · 팔 위쪽 · 멜란지 작업", "placeEn": "Upper arm", "placeKo": "팔 위쪽"},
  {"id": "custom-066", "cat": "dragon", "w": 1602, "h": 2000, "en": "Dragon tattoo in blue ink on the full arm, by Melange", "ko": "용 타투, 푸른 잉크 · 팔 전체 · 멜란지 작업", "placeEn": "Full arm", "placeKo": "팔 전체"},
  {"id": "custom-067", "cat": "pattern", "w": 1501, "h": 2000, "en": "Pattern tattoo in blue ink on the chest, by Melange", "ko": "패턴 타투, 푸른 잉크 · 가슴 · 멜란지 작업", "placeEn": "Chest", "placeKo": "가슴"},
  {"id": "custom-068", "cat": "dragon", "w": 1600, "h": 2000, "en": "Dragon tattoo in blue ink on the forearm, by Melange", "ko": "용 타투, 푸른 잉크 · 팔뚝 · 멜란지 작업", "placeEn": "Forearm", "placeKo": "팔뚝"},
  {"id": "custom-069", "cat": "pattern", "w": 1602, "h": 2000, "en": "Pattern tattoo in blue ink on the upper arm, by Melange", "ko": "패턴 타투, 푸른 잉크 · 팔 위쪽 · 멜란지 작업", "placeEn": "Upper arm", "placeKo": "팔 위쪽"},
  {"id": "custom-070", "cat": "snake", "w": 1600, "h": 2000, "en": "Snake tattoo in blue ink on the upper arm, by Melange", "ko": "뱀 타투, 푸른 잉크 · 팔 위쪽 · 멜란지 작업", "placeEn": "Upper arm", "placeKo": "팔 위쪽"},
  {"id": "custom-071", "cat": "dragon", "w": 1602, "h": 2000, "en": "Dragon tattoo in blue ink on the back, by Melange", "ko": "용 타투, 푸른 잉크 · 등 · 멜란지 작업", "placeEn": "Back", "placeKo": "등"},
  {"id": "custom-072", "cat": "pattern", "w": 1125, "h": 2000, "en": "Pattern tattoo in blue ink on the ribs, by Melange", "ko": "패턴 타투, 푸른 잉크 · 옆구리 · 멜란지 작업", "placeEn": "Ribs", "placeKo": "옆구리"},
  {"id": "custom-073", "cat": "pattern", "w": 1125, "h": 2000, "en": "Pattern tattoo in blue ink on the leg, by Melange", "ko": "패턴 타투, 푸른 잉크 · 다리 · 멜란지 작업", "placeEn": "Leg", "placeKo": "다리"},
  {"id": "custom-074", "cat": "pattern", "w": 1602, "h": 2000, "en": "Pattern tattoo in blue ink on the forearm, by Melange", "ko": "패턴 타투, 푸른 잉크 · 팔뚝 · 멜란지 작업", "placeEn": "Forearm", "placeKo": "팔뚝"},
  {"id": "custom-075", "cat": "character", "w": 1333, "h": 2000, "en": "Dragonair, blue ink character tattoo on the upper arm", "ko": "신뇽, 푸른 잉크 캐릭터 타투 (팔 위쪽)", "placeEn": "Upper arm", "placeKo": "팔 위쪽"},
  {"id": "custom-076", "cat": "more", "w": 1600, "h": 2000, "en": "Custom tattoo in blue ink on the upper arm, by Melange", "ko": "커스텀 타투, 푸른 잉크 · 팔 위쪽 · 멜란지 작업", "placeEn": "Upper arm", "placeKo": "팔 위쪽"},
  {"id": "custom-077", "cat": "pattern", "w": 1501, "h": 2000, "en": "Pattern tattoo in blue ink on the back, by Melange", "ko": "패턴 타투, 푸른 잉크 · 등 · 멜란지 작업", "placeEn": "Back", "placeKo": "등"},
  {"id": "custom-078", "cat": "pattern", "w": 1600, "h": 2000, "en": "Pattern tattoo in blue ink on the neck, by Melange", "ko": "패턴 타투, 푸른 잉크 · 목 · 멜란지 작업", "placeEn": "Neck", "placeKo": "목"},
  {"id": "custom-079", "cat": "pattern", "w": 1501, "h": 2000, "en": "Pattern tattoo in blue ink on the head, by Melange", "ko": "패턴 타투, 푸른 잉크 · 머리 · 멜란지 작업", "placeEn": "Head", "placeKo": "머리"},
  {"id": "custom-080", "cat": "dragon", "w": 1501, "h": 2000, "en": "Dragon tattoo in blue ink on the full arm, by Melange", "ko": "용 타투, 푸른 잉크 · 팔 전체 · 멜란지 작업", "placeEn": "Full arm", "placeKo": "팔 전체"},
  {"id": "custom-081", "cat": "more", "w": 1602, "h": 2000, "en": "Custom tattoo in blue ink on the upper arm, by Melange", "ko": "커스텀 타투, 푸른 잉크 · 팔 위쪽 · 멜란지 작업", "placeEn": "Upper arm", "placeKo": "팔 위쪽"},
  {"id": "custom-082", "cat": "pattern", "w": 1501, "h": 2000, "en": "Pattern tattoo in blue ink on the full arm, by Melange", "ko": "패턴 타투, 푸른 잉크 · 팔 전체 · 멜란지 작업", "placeEn": "Full arm", "placeKo": "팔 전체"},
  {"id": "custom-083", "cat": "pattern", "w": 1501, "h": 2000, "en": "Pattern tattoo in blue ink on the forearm, by Melange", "ko": "패턴 타투, 푸른 잉크 · 팔뚝 · 멜란지 작업", "placeEn": "Forearm", "placeKo": "팔뚝"},
  {"id": "custom-084", "cat": "pattern", "w": 1602, "h": 2000, "en": "Pattern tattoo in blue ink on the forearm, by Melange", "ko": "패턴 타투, 푸른 잉크 · 팔뚝 · 멜란지 작업", "placeEn": "Forearm", "placeKo": "팔뚝"},
  {"id": "custom-085", "cat": "animal", "w": 1501, "h": 2000, "en": "Deer tattoo in blue ink, by Melange", "ko": "사슴 타투, 푸른 잉크 · 멜란지 작업", "placeEn": "", "placeKo": ""},
  {"id": "custom-086", "cat": "dragon", "w": 1602, "h": 2000, "en": "Dragon tattoo in blue ink on the forearm, by Melange", "ko": "용 타투, 푸른 잉크 · 팔뚝 · 멜란지 작업", "placeEn": "Forearm", "placeKo": "팔뚝"},
  {"id": "custom-087", "cat": "dragon", "w": 1501, "h": 2000, "en": "Dragon tattoo in blue ink on the full arm, by Melange", "ko": "용 타투, 푸른 잉크 · 팔 전체 · 멜란지 작업", "placeEn": "Full arm", "placeKo": "팔 전체"},
  {"id": "custom-088", "cat": "pattern", "w": 1602, "h": 2000, "en": "Pattern tattoo in blue ink on the shoulder, by Melange", "ko": "패턴 타투, 푸른 잉크 · 어깨 · 멜란지 작업", "placeEn": "Shoulder", "placeKo": "어깨"},
  {"id": "custom-089", "cat": "pattern", "w": 1600, "h": 2131, "en": "Pattern tattoo in blue ink on the full arm, by Melange", "ko": "패턴 타투, 푸른 잉크 · 팔 전체 · 멜란지 작업", "placeEn": "Full arm", "placeKo": "팔 전체"},
  {"id": "custom-090", "cat": "more", "w": 1600, "h": 1997, "en": "Custom tattoo in blue ink on the forearm, by Melange", "ko": "커스텀 타투, 푸른 잉크 · 팔뚝 · 멜란지 작업", "placeEn": "Forearm", "placeKo": "팔뚝"},
  {"id": "custom-091", "cat": "character", "w": 1600, "h": 2131, "en": "Little devil, blue ink character tattoo on the upper arm", "ko": "꼬마 악마, 푸른 잉크 캐릭터 타투 (팔 위쪽)", "placeEn": "Upper arm", "placeKo": "팔 위쪽"},
  {"id": "custom-092", "cat": "more", "w": 1600, "h": 1997, "en": "Custom tattoo in blue ink on the upper arm, by Melange", "ko": "커스텀 타투, 푸른 잉크 · 팔 위쪽 · 멜란지 작업", "placeEn": "Upper arm", "placeKo": "팔 위쪽"},
  {"id": "custom-093", "cat": "floral", "w": 1600, "h": 2400, "en": "Flower tattoo in blue ink on the knee, by Melange", "ko": "꽃 타투, 푸른 잉크 · 무릎 · 멜란지 작업", "placeEn": "Knee", "placeKo": "무릎"},
  {"id": "custom-094", "cat": "pattern", "w": 1600, "h": 2400, "en": "Pattern tattoo in blue ink on the head, by Melange", "ko": "패턴 타투, 푸른 잉크 · 머리 · 멜란지 작업", "placeEn": "Head", "placeKo": "머리"},
  {"id": "custom-095", "cat": "dragon", "w": 1600, "h": 2131, "en": "Dragon tattoo in blue ink on the upper arm, by Melange", "ko": "용 타투, 푸른 잉크 · 팔 위쪽 · 멜란지 작업", "placeEn": "Upper arm", "placeKo": "팔 위쪽"},
  {"id": "custom-096", "cat": "floral", "w": 1600, "h": 2000, "en": "Flower tattoo in blue ink on the full arm, by Melange", "ko": "꽃 타투, 푸른 잉크 · 팔 전체 · 멜란지 작업", "placeEn": "Full arm", "placeKo": "팔 전체"},
  {"id": "custom-097", "cat": "floral", "w": 1600, "h": 2000, "en": "Flower tattoo in blue ink on the upper arm, by Melange", "ko": "꽃 타투, 푸른 잉크 · 팔 위쪽 · 멜란지 작업", "placeEn": "Upper arm", "placeKo": "팔 위쪽"},
  {"id": "custom-098", "cat": "more", "w": 1600, "h": 2131, "en": "Custom tattoo in blue ink on the upper arm, by Melange", "ko": "커스텀 타투, 푸른 잉크 · 팔 위쪽 · 멜란지 작업", "placeEn": "Upper arm", "placeKo": "팔 위쪽"},
  {"id": "custom-099", "cat": "more", "w": 1600, "h": 998, "en": "Custom tattoo in blue ink on the chest, by Melange", "ko": "커스텀 타투, 푸른 잉크 · 가슴 · 멜란지 작업", "placeEn": "Chest", "placeKo": "가슴"},
  {"id": "custom-100", "cat": "snake", "w": 1600, "h": 1997, "en": "Snake tattoo in blue ink on the forearm, by Melange", "ko": "뱀 타투, 푸른 잉크 · 팔뚝 · 멜란지 작업", "placeEn": "Forearm", "placeKo": "팔뚝"},
  {"id": "custom-101", "cat": "pattern", "w": 1600, "h": 2131, "en": "Pattern tattoo in blue ink on the chest, by Melange", "ko": "패턴 타투, 푸른 잉크 · 가슴 · 멜란지 작업", "placeEn": "Chest", "placeKo": "가슴"},
  {"id": "custom-102", "cat": "dragon", "w": 1600, "h": 2131, "en": "Dragon tattoo in blue ink on the ribs, by Melange", "ko": "용 타투, 푸른 잉크 · 옆구리 · 멜란지 작업", "placeEn": "Ribs", "placeKo": "옆구리"},
  {"id": "custom-103", "cat": "dragon", "w": 1600, "h": 2000, "en": "Dragon tattoo in blue ink on the thigh, by Melange", "ko": "용 타투, 푸른 잉크 · 허벅지 · 멜란지 작업", "placeEn": "Thigh", "placeKo": "허벅지"},
  {"id": "custom-104", "cat": "dragon", "w": 1600, "h": 2131, "en": "Dragon tattoo in blue ink on the full arm, by Melange", "ko": "용 타투, 푸른 잉크 · 팔 전체 · 멜란지 작업", "placeEn": "Full arm", "placeKo": "팔 전체"},
  {"id": "custom-105", "cat": "character", "w": 1600, "h": 2000, "en": "Piplup, blue ink character tattoo on the forearm", "ko": "팽도리, 푸른 잉크 캐릭터 타투 (팔뚝)", "placeEn": "Forearm", "placeKo": "팔뚝"},
  {"id": "custom-106", "cat": "more", "w": 1600, "h": 1997, "en": "Custom tattoo in blue ink on the upper arm, by Melange", "ko": "커스텀 타투, 푸른 잉크 · 팔 위쪽 · 멜란지 작업", "placeEn": "Upper arm", "placeKo": "팔 위쪽"},
  {"id": "custom-107", "cat": "dragon", "w": 1600, "h": 2000, "en": "Dragon tattoo in blue ink on the thigh, by Melange", "ko": "용 타투, 푸른 잉크 · 허벅지 · 멜란지 작업", "placeEn": "Thigh", "placeKo": "허벅지"},
  {"id": "custom-108", "cat": "pattern", "w": 1600, "h": 1998, "en": "Pattern tattoo in blue ink on the forearm, by Melange", "ko": "패턴 타투, 푸른 잉크 · 팔뚝 · 멜란지 작업", "placeEn": "Forearm", "placeKo": "팔뚝"},
  {"id": "flash-01", "cat": "more", "w": 1400, "h": 1750, "en": "Flash sheet of available designs by Melange", "ko": "멜란지 도안 플래시 시트", "placeEn": "", "placeKo": ""},
];
