/* Melange Tattoo — gallery data.
   Newest first. To add a photo: put <id>-480.webp and <id>-1080.webp in assets/work/
   and add a line at the top. cat is one of: dragon, koi, snake, wave, floral, character, more. */
window.MELANGE_GALLERY = [
  {"id": "custom-109", "cat": "character", "w": 1600, "h": 2000, "en": "Stitch, blue ink character tattoo", "ko": "스티치, 푸른 잉크 캐릭터 타투", "placeEn": "", "placeKo": ""},
  {"id": "custom-110", "cat": "character", "w": 1501, "h": 2000, "en": "Blastoise, blue ink character tattoo", "ko": "거북왕, 푸른 잉크 캐릭터 타투", "placeEn": "", "placeKo": ""},
  {"id": "custom-111", "cat": "character", "w": 1602, "h": 2000, "en": "Oshawott, blue ink character tattoo", "ko": "수댕이, 푸른 잉크 캐릭터 타투", "placeEn": "", "placeKo": ""},
  {"id": "custom-112", "cat": "character", "w": 1501, "h": 2000, "en": "Boba Fett, blue ink character tattoo", "ko": "보바 펫, 푸른 잉크 캐릭터 타투", "placeEn": "Forearm", "placeKo": "팔뚝"},
  {"id": "custom-113", "cat": "character", "w": 1501, "h": 2000, "en": "Vaporeon, blue ink character tattoo", "ko": "샤미드, 푸른 잉크 캐릭터 타투", "placeEn": "", "placeKo": ""},
  {"id": "custom-114", "cat": "character", "w": 1500, "h": 2000, "en": "Kyogre, blue ink character tattoo", "ko": "가이오가, 푸른 잉크 캐릭터 타투", "placeEn": "Forearm", "placeKo": "팔뚝"},
  {"id": "dragon-01", "cat": "dragon", "w": 1600, "h": 2131, "en": "Dragon", "ko": "", "placeEn": "", "placeKo": ""},
  {"id": "snake-01", "cat": "snake", "w": 1600, "h": 2131, "en": "Snake", "ko": "", "placeEn": "", "placeKo": ""},
  {"id": "phoenix-01", "cat": "more", "w": 1600, "h": 2131, "en": "Phoenix", "ko": "", "placeEn": "", "placeKo": ""},
  {"id": "flowers-01", "cat": "floral", "w": 1600, "h": 2131, "en": "Flowers", "ko": "", "placeEn": "", "placeKo": ""},
  {"id": "clouds-01", "cat": "more", "w": 1600, "h": 2131, "en": "Clouds", "ko": "", "placeEn": "", "placeKo": ""},
  {"id": "lightning-01", "cat": "more", "w": 1600, "h": 2131, "en": "Lightning", "ko": "", "placeEn": "", "placeKo": ""},
  {"id": "pattern-01", "cat": "wave", "w": 1600, "h": 2131, "en": "Pattern", "ko": "", "placeEn": "", "placeKo": ""},
  {"id": "dragon-02", "cat": "dragon", "w": 1600, "h": 2131, "en": "Dragon", "ko": "", "placeEn": "", "placeKo": ""},
  {"id": "phoenix-02", "cat": "more", "w": 1600, "h": 2131, "en": "Phoenix", "ko": "", "placeEn": "", "placeKo": ""},
  {"id": "pattern-02", "cat": "wave", "w": 1600, "h": 2131, "en": "Pattern", "ko": "", "placeEn": "", "placeKo": ""},
  {"id": "pattern-03", "cat": "wave", "w": 1600, "h": 2131, "en": "Pattern", "ko": "", "placeEn": "", "placeKo": ""},
  {"id": "custom-001", "cat": "dragon", "w": 1501, "h": 2000, "en": "upper arm dragon tattoos, matching pair in red and blue", "ko": "팔뚝 위쪽 용 타투, 빨간색과 파란색 매칭 한 쌍", "placeEn": "Upper arm", "placeKo": "팔 위쪽"},
  {"id": "custom-002", "cat": "more", "w": 1501, "h": 2000, "en": "forearm portrait tattoo, blue painted style", "ko": "팔뚝 여성 초상화 타투, 파란색 페인팅 스타일", "placeEn": "Forearm", "placeKo": "팔뚝"},
  {"id": "custom-003", "cat": "more", "w": 1602, "h": 2000, "en": "forearm skull and sword design, blue ink", "ko": "팔뚝 해골과 검 디자인, 파란색 잉크", "placeEn": "Forearm", "placeKo": "팔뚝"},
  {"id": "custom-004", "cat": "dragon", "w": 1501, "h": 2000, "en": "forearm dragon sleeve, blue with orange clouds", "ko": "팔뚝 용 슬리브, 파란색과 주황 구름", "placeEn": "Forearm", "placeKo": "팔뚝"},
  {"id": "custom-005", "cat": "more", "w": 1501, "h": 2000, "en": "ribs Hindu goddess tattoo with skull necklace", "ko": "옆구리 힌두 여신 타투, 해골 목걸이", "placeEn": "Ribs", "placeKo": "옆구리"},
  {"id": "custom-006", "cat": "wave", "w": 1501, "h": 2000, "en": "forearm wave pattern with bat and stars, blue and pink ink", "ko": "팔뚝 파도 패턴과 박쥐, 별 장식, 파란색과 핑크 잉크", "placeEn": "Forearm", "placeKo": "팔뚝"},
  {"id": "custom-007", "cat": "floral", "w": 1600, "h": 2000, "en": "forearm ornamental mask design with cherry blossoms, pink ink", "ko": "팔뚝 장식 가면 디자인과 벚꽃, 핑크 잉크", "placeEn": "Forearm", "placeKo": "팔뚝"},
  {"id": "custom-008", "cat": "more", "w": 1125, "h": 2000, "en": "forearm sword tattoo, black linework", "ko": "팔뚝 검 타투, 블랙 라인워크", "placeEn": "Forearm", "placeKo": "팔뚝"},
  {"id": "custom-009", "cat": "more", "w": 1501, "h": 2000, "en": "forearm ornamental turtle design, blue and orange", "ko": "팔뚝 장식 거북이 디자인, 파란색과 주황색", "placeEn": "Forearm", "placeKo": "팔뚝"},
  {"id": "custom-010", "cat": "more", "w": 1501, "h": 2000, "en": "forearm abstract flame design, purple and blue", "ko": "팔뚝 추상 불꽃 디자인, 보라색과 파란색", "placeEn": "Forearm", "placeKo": "팔뚝"},
  {"id": "custom-011", "cat": "floral", "w": 1600, "h": 2000, "en": "shoulder geometric pattern with flowers, blue ink", "ko": "어깨 기하학 패턴과 꽃, 파란색 잉크", "placeEn": "Shoulder", "placeKo": "어깨"},
  {"id": "custom-012", "cat": "more", "w": 1501, "h": 2000, "en": "upper back wing design, blue ink", "ko": "등 위쪽 날개 디자인, 파란색 잉크", "placeEn": "Back", "placeKo": "등"},
  {"id": "custom-013", "cat": "more", "w": 1602, "h": 2000, "en": "shin tribal flame pattern, red and black", "ko": "정강이 트라이벌 화염 패턴, 빨간색과 검정색", "placeEn": "Leg", "placeKo": "다리"},
  {"id": "custom-014", "cat": "dragon", "w": 1501, "h": 2000, "en": "full arm dragon sleeve, deep blue with wave details", "ko": "팔 전체 용 슬리브, 짙은 파란색과 파도 디테일", "placeEn": "Full arm", "placeKo": "팔 전체"},
  {"id": "custom-015", "cat": "more", "w": 1501, "h": 2000, "en": "upper arm dagger tattoo, blue ink", "ko": "팔뚝 위쪽 단검 타투, 파란색 잉크", "placeEn": "Upper arm", "placeKo": "팔 위쪽"},
  {"id": "custom-016", "cat": "more", "w": 1501, "h": 2000, "en": "forearm ornamental sleeve, blue scrollwork", "ko": "팔뚝 장식 슬리브, 파란색 스크롤 패턴", "placeEn": "Forearm", "placeKo": "팔뚝"},
  {"id": "custom-017", "cat": "floral", "w": 1501, "h": 2000, "en": "upper arm flower vase tattoo, pink and yellow bouquet", "ko": "팔뚝 위쪽 꽃병 타투, 핑크와 노란 꽃다발", "placeEn": "Upper arm", "placeKo": "팔 위쪽"},
  {"id": "custom-018", "cat": "wave", "w": 1501, "h": 2000, "en": "full arm ornamental wave sleeve, pink and red", "ko": "팔 전체 장식 파도 슬리브, 핑크와 빨간색", "placeEn": "Full arm", "placeKo": "팔 전체"},
  {"id": "custom-019", "cat": "wave", "w": 1600, "h": 2000, "en": "back of neck wave design, blue ink", "ko": "목 뒤 파도 디자인, 파란색 잉크", "placeEn": "Back", "placeKo": "등"},
  {"id": "custom-020", "cat": "more", "w": 1600, "h": 2000, "en": "inner arm ornamental cross tattoo, blue ink", "ko": "팔 안쪽 장식 십자 타투, 파란색 잉크", "placeEn": "Inner arm", "placeKo": "팔 안쪽"},
  {"id": "custom-021", "cat": "dragon", "w": 1125, "h": 2000, "en": "forearm dragon and wave design, blue linework", "ko": "팔뚝 용과 파도 디자인, 파란색 라인워크", "placeEn": "Forearm", "placeKo": "팔뚝"},
  {"id": "custom-022", "cat": "more", "w": 1333, "h": 2000, "en": "full arm ornamental sleeve, blue and orange", "ko": "팔 전체 장식 슬리브, 파란색과 주황색", "placeEn": "Full arm", "placeKo": "팔 전체"},
  {"id": "custom-023", "cat": "floral", "w": 1600, "h": 2000, "en": "collarbone floral vine tattoo, blue ink, symmetrical pair", "ko": "쇄골 꽃 넝쿨 타투, 파란색 잉크, 대칭 디자인", "placeEn": "Collarbone", "placeKo": "쇄골"},
  {"id": "custom-024", "cat": "more", "w": 2000, "h": 1333, "en": "chest ornamental wing piece, blue ink", "ko": "가슴 장식 날개 디자인, 파란색 잉크", "placeEn": "Chest", "placeKo": "가슴"},
  {"id": "custom-025", "cat": "wave", "w": 1600, "h": 2000, "en": "inner elbow wave heart tattoo, blue ink", "ko": "팔 안쪽 파도 하트 타투, 파란색 잉크", "placeEn": "Inner arm", "placeKo": "팔 안쪽"},
  {"id": "custom-026", "cat": "more", "w": 1600, "h": 2000, "en": "inner arm butterfly tattoo, blue and orange", "ko": "팔 안쪽 나비 타투, 파란색과 주황색", "placeEn": "Inner arm", "placeKo": "팔 안쪽"},
  {"id": "custom-027", "cat": "floral", "w": 1333, "h": 2000, "en": "full arm geometric floral sleeve, blue ink", "ko": "팔 전체 기하학 꽃무늬 슬리브, 파란색 잉크", "placeEn": "Full arm", "placeKo": "팔 전체"},
  {"id": "custom-028", "cat": "dragon", "w": 1602, "h": 2000, "en": "shoulder dragon tattoo, black and grey with blue wave", "ko": "어깨 용 타투, 흑회색과 파란 파도", "placeEn": "Shoulder", "placeKo": "어깨"},
  {"id": "custom-029", "cat": "wave", "w": 1602, "h": 2000, "en": "forearm ornamental wave design with gem accents, blue ink", "ko": "팔뚝 장식 파도 디자인과 보석 장식, 파란색 잉크", "placeEn": "Forearm", "placeKo": "팔뚝"},
  {"id": "custom-030", "cat": "floral", "w": 1501, "h": 2000, "en": "side neck cherry blossom branch tattoo, blue ink", "ko": "목 옆 벚꽃 가지 타투, 파란색 잉크", "placeEn": "Ribs", "placeKo": "옆구리"},
  {"id": "custom-031", "cat": "floral", "w": 1600, "h": 2000, "en": "forearm tattoo collection, small symbols and lotus flower", "ko": "팔뚝 작은 심볼과 연꽃 모음 타투", "placeEn": "Forearm", "placeKo": "팔뚝"},
  {"id": "custom-032", "cat": "wave", "w": 1600, "h": 2000, "en": "ribs ornamental wave design with eye motif, blue ink", "ko": "옆구리 장식 파도 디자인과 눈 모티프, 파란색 잉크", "placeEn": "Ribs", "placeKo": "옆구리"},
  {"id": "custom-033", "cat": "more", "w": 1501, "h": 2000, "en": "back angel warrior piece, blue and black", "ko": "등 천사 전사 디자인, 파란색과 검정색", "placeEn": "Back", "placeKo": "등"},
  {"id": "custom-034", "cat": "dragon", "w": 2000, "h": 1333, "en": "collarbone dragon tattoo, mirrored pair in black and blue", "ko": "쇄골 쌍용 타투, 검정색과 파란색", "placeEn": "Collarbone", "placeKo": "쇄골"},
  {"id": "custom-035", "cat": "snake", "w": 1600, "h": 2000, "en": "forearm tiger and snake design, blue and white", "ko": "팔뚝 호랑이와 뱀 디자인, 파란색과 흰색", "placeEn": "Forearm", "placeKo": "팔뚝"},
  {"id": "custom-036", "cat": "dragon", "w": 1600, "h": 2000, "en": "shoulder-to-collarbone dragon tattoo, mirrored pair, close-up view", "ko": "어깨부터 쇄골까지 쌍용 타투, 근접 사진", "placeEn": "Shoulder", "placeKo": "어깨"},
  {"id": "custom-037", "cat": "koi", "w": 1501, "h": 2000, "en": "forearm koi fish and flowers tattoo, blue ink", "ko": "팔뚝 잉어와 꽃 타투, 파란색 잉크", "placeEn": "Forearm", "placeKo": "팔뚝"},
  {"id": "custom-038", "cat": "floral", "w": 1500, "h": 2000, "en": "upper arm floral ribbon sleeve, blue ink", "ko": "팔뚝 위쪽 꽃과 리본 슬리브, 파란색 잉크", "placeEn": "Upper arm", "placeKo": "팔 위쪽"},
  {"id": "custom-039", "cat": "floral", "w": 1600, "h": 2000, "en": "forearm flower medallion tattoo, blue and gold", "ko": "팔뚝 꽃 메달리온 타투, 파란색과 금색", "placeEn": "Forearm", "placeKo": "팔뚝"},
  {"id": "custom-040", "cat": "dragon", "w": 1602, "h": 2000, "en": "ribs dragon and floral linework, black ink", "ko": "옆구리 용과 꽃 라인워크, 블랙 잉크", "placeEn": "Ribs", "placeKo": "옆구리"},
  {"id": "custom-041", "cat": "more", "w": 1501, "h": 2000, "en": "calf ornamental cat tattoo, blue ink", "ko": "종아리 장식 고양이 타투, 파란색 잉크", "placeEn": "Leg", "placeKo": "다리"},
  {"id": "custom-042", "cat": "more", "w": 1602, "h": 2000, "en": "shoulder blade swallow tattoo, blue ink", "ko": "어깨뼈 제비 타투, 파란색 잉크", "placeEn": "Shoulder", "placeKo": "어깨"},
  {"id": "custom-043", "cat": "more", "w": 1602, "h": 2000, "en": "upper arm abstract calligraphy design, blue ink", "ko": "팔뚝 위쪽 추상 캘리그래피 디자인, 파란색 잉크", "placeEn": "Upper arm", "placeKo": "팔 위쪽"},
  {"id": "custom-044", "cat": "floral", "w": 1600, "h": 2000, "en": "upper arm flower vase tattoo, orange flowers", "ko": "팔뚝 위쪽 꽃병 타투, 주황색 꽃", "placeEn": "Upper arm", "placeKo": "팔 위쪽"},
  {"id": "custom-045", "cat": "more", "w": 1602, "h": 2000, "en": "forearm tribal branch pattern, blue ink", "ko": "팔뚝 트라이벌 나뭇가지 패턴, 파란색 잉크", "placeEn": "Forearm", "placeKo": "팔뚝"},
  {"id": "custom-046", "cat": "more", "w": 1501, "h": 2000, "en": "hand tattoo with eyes and stars, blue ink", "ko": "손등 눈과 별 타투, 파란색 잉크", "placeEn": "Hand", "placeKo": "손"},
  {"id": "custom-047", "cat": "floral", "w": 1602, "h": 2000, "en": "upper arm chrysanthemum flower tattoo, blue ink", "ko": "팔뚝 위쪽 국화 타투, 파란색 잉크", "placeEn": "Upper arm", "placeKo": "팔 위쪽"},
  {"id": "custom-048", "cat": "dragon", "w": 1602, "h": 2000, "en": "upper arm dragon tattoo, green with red accents", "ko": "팔뚝 위쪽 용 타투, 초록색과 빨간색", "placeEn": "Upper arm", "placeKo": "팔 위쪽"},
  {"id": "custom-049", "cat": "dragon", "w": 1501, "h": 2000, "en": "forearm dragon tattoo, teal ink, coiled wave design", "ko": "팔뚝 용 타투, 청록색 잉크, 파도처럼 휘감긴 디자인", "placeEn": "Forearm", "placeKo": "팔뚝"},
  {"id": "custom-050", "cat": "snake", "w": 1602, "h": 2000, "en": "forearm snake tattoo, blue ink with star accent", "ko": "팔뚝 뱀 타투, 파란색 잉크와 별 장식", "placeEn": "Forearm", "placeKo": "팔뚝"},
  {"id": "custom-051", "cat": "more", "w": 1501, "h": 2000, "en": "upper arm hexagon pattern tattoo, blue ornamental center", "ko": "팔뚝 위쪽 육각형 패턴 타투, 파란색 장식 중앙", "placeEn": "Upper arm", "placeKo": "팔 위쪽"},
  {"id": "custom-052", "cat": "more", "w": 1602, "h": 2000, "en": "forearm panther tattoo, blue ink", "ko": "팔뚝 표범 타투, 파란색 잉크", "placeEn": "Forearm", "placeKo": "팔뚝"},
  {"id": "custom-053", "cat": "dragon", "w": 1602, "h": 2000, "en": "thigh dragon tattoo, black with blue flames", "ko": "허벅지 용 타투, 검정색과 파란 불꽃", "placeEn": "Thigh", "placeKo": "허벅지"},
  {"id": "custom-054", "cat": "floral", "w": 1125, "h": 2000, "en": "upper arm fox mask tattoo with flower burst, red and white", "ko": "팔뚝 위쪽 여우 가면 타투와 꽃 장식, 빨간색과 흰색", "placeEn": "Upper arm", "placeKo": "팔 위쪽"},
  {"id": "custom-055", "cat": "floral", "w": 1602, "h": 2000, "en": "forearm floral vine tattoo, blue ink", "ko": "팔뚝 꽃 넝쿨 타투, 파란색 잉크", "placeEn": "Forearm", "placeKo": "팔뚝"},
  {"id": "custom-056", "cat": "more", "w": 1501, "h": 2000, "en": "forearm warrior figure tattoo, blue ink", "ko": "팔뚝 전사 캐릭터 타투, 파란색 잉크", "placeEn": "Forearm", "placeKo": "팔뚝"},
  {"id": "custom-057", "cat": "dragon", "w": 1602, "h": 2000, "en": "upper arm dragon tattoo, black with blue flames and dragonfly accent", "ko": "팔뚝 위쪽 용 타투, 검정색과 파란 불꽃, 잠자리 장식", "placeEn": "Upper arm", "placeKo": "팔 위쪽"},
  {"id": "custom-058", "cat": "wave", "w": 1600, "h": 2000, "en": "forearm wave and thorn pattern, teal ink", "ko": "팔뚝 파도와 가시 패턴, 청록색 잉크", "placeEn": "Forearm", "placeKo": "팔뚝"},
  {"id": "custom-059", "cat": "more", "w": 1600, "h": 2000, "en": "upper arm cartoon cat tattoo with tiny bird, blue and orange", "ko": "팔뚝 위쪽 만화 고양이 타투, 작은 새와 함께, 파란색과 주황색", "placeEn": "Upper arm", "placeKo": "팔 위쪽"},
  {"id": "custom-060", "cat": "more", "w": 1501, "h": 2000, "en": "forearm ornamental vase tattoo, dark blue", "ko": "팔뚝 장식 항아리 타투, 짙은 파란색", "placeEn": "Forearm", "placeKo": "팔뚝"},
  {"id": "custom-061", "cat": "koi", "w": 1125, "h": 2000, "en": "forearm koi fish tattoo with crescent moon accents, blue ink", "ko": "팔뚝 잉어 타투, 파란색 잉크, 초승달 장식", "placeEn": "Forearm", "placeKo": "팔뚝"},
  {"id": "custom-062", "cat": "dragon", "w": 1602, "h": 2000, "en": "inner arm dragon tattoo, black and blue", "ko": "팔 안쪽 용 타투, 검정색과 파란색", "placeEn": "Inner arm", "placeKo": "팔 안쪽"},
  {"id": "custom-063", "cat": "floral", "w": 1602, "h": 2000, "en": "upper arm peony flower tattoo, blue ink", "ko": "팔뚝 위쪽 작약 타투, 파란색 잉크", "placeEn": "Upper arm", "placeKo": "팔 위쪽"},
  {"id": "custom-064", "cat": "snake", "w": 1429, "h": 2000, "en": "forearm snake and dagger tattoo, red and blue", "ko": "팔뚝 뱀과 단검 타투, 빨간색과 파란색", "placeEn": "Forearm", "placeKo": "팔뚝"},
  {"id": "custom-065", "cat": "more", "w": 1501, "h": 2000, "en": "upper arm butterfly tattoo, blue with gold trim", "ko": "팔뚝 위쪽 나비 타투, 파란색과 금색 테두리", "placeEn": "Upper arm", "placeKo": "팔 위쪽"},
  {"id": "custom-066", "cat": "dragon", "w": 1602, "h": 2000, "en": "full arm dragon sleeve, orange and blue", "ko": "팔 전체 용 슬리브, 주황색과 파란색", "placeEn": "Full arm", "placeKo": "팔 전체"},
  {"id": "custom-067", "cat": "more", "w": 1501, "h": 2000, "en": "chest ornamental pattern tattoo, blue ink", "ko": "가슴 장식 패턴 타투, 파란색 잉크", "placeEn": "Chest", "placeKo": "가슴"},
  {"id": "custom-068", "cat": "snake", "w": 1600, "h": 2000, "en": "forearm snake tattoo with red flowers, black ink", "ko": "팔뚝 뱀과 빨간 꽃 타투, 블랙 잉크", "placeEn": "Forearm", "placeKo": "팔뚝"},
  {"id": "custom-069", "cat": "more", "w": 1602, "h": 2000, "en": "upper arm paisley pattern tattoo, multicolor", "ko": "팔뚝 위쪽 페이즐리 패턴 타투, 멀티컬러", "placeEn": "Upper arm", "placeKo": "팔 위쪽"},
  {"id": "custom-070", "cat": "dragon", "w": 1600, "h": 2000, "en": "upper arm dragon tattoo, blue ink with wave scrollwork", "ko": "팔뚝 위쪽 용 타투, 파란색 잉크와 파도 스크롤", "placeEn": "Upper arm", "placeKo": "팔 위쪽"},
  {"id": "custom-071", "cat": "dragon", "w": 1602, "h": 2000, "en": "upper back dragon tattoo, dark blue, looping design", "ko": "등 위쪽 용 타투, 짙은 파란색, 고리 모양 디자인", "placeEn": "Back", "placeKo": "등"},
  {"id": "custom-072", "cat": "more", "w": 1125, "h": 2000, "en": "back ornamental linework tattoo, black and grey", "ko": "등 장식 라인워크 타투, 흑회색", "placeEn": "Back", "placeKo": "등"},
  {"id": "custom-073", "cat": "more", "w": 1501, "h": 2000, "en": "shin tribal heart pattern, blue ink", "ko": "정강이 트라이벌 하트 패턴, 파란색 잉크", "placeEn": "Leg", "placeKo": "다리"},
  {"id": "custom-074", "cat": "wave", "w": 1602, "h": 2000, "en": "forearm ornamental wave sleeve, teal and tan", "ko": "팔뚝 장식 파도 슬리브, 청록색과 황토색", "placeEn": "Forearm", "placeKo": "팔뚝"},
  {"id": "custom-075", "cat": "dragon", "w": 1333, "h": 2000, "en": "thigh dragon tattoo, blue ink with flower accent", "ko": "허벅지 용 타투, 파란색 잉크와 꽃 장식", "placeEn": "Thigh", "placeKo": "허벅지"},
  {"id": "custom-076", "cat": "more", "w": 1600, "h": 2000, "en": "upper arm skull tattoo, blue ink, melting mirror frame", "ko": "팔뚝 위쪽 해골 타투, 파란색 잉크, 녹아내리는 액자 모양", "placeEn": "Upper arm", "placeKo": "팔 위쪽"},
  {"id": "custom-077", "cat": "more", "w": 1501, "h": 2000, "en": "upper back branching pattern tattoo, blue and black", "ko": "등 위쪽 나뭇가지 패턴 타투, 파란색과 검정색", "placeEn": "Back", "placeKo": "등"},
  {"id": "custom-078", "cat": "more", "w": 1600, "h": 2000, "en": "shoulder abstract brushstroke tattoo, black ink", "ko": "어깨 추상 붓터치 타투, 블랙 잉크", "placeEn": "Shoulder", "placeKo": "어깨"},
  {"id": "custom-079", "cat": "more", "w": 1501, "h": 2000, "en": "cheek ornamental swirl tattoo, blue ink", "ko": "볼 장식 소용돌이 타투, 파란색 잉크", "placeEn": "Neck & face", "placeKo": "목·얼굴"},
  {"id": "custom-080", "cat": "dragon", "w": 1501, "h": 2000, "en": "full arm dragon sleeve, teal blue with cloud accents", "ko": "팔 전체 용 슬리브, 청록색과 구름 장식", "placeEn": "Full arm", "placeKo": "팔 전체"},
  {"id": "custom-081", "cat": "more", "w": 1602, "h": 2000, "en": "upper arm ornamental dagger tattoo, blue ink", "ko": "팔뚝 위쪽 장식 단검 타투, 파란색 잉크", "placeEn": "Upper arm", "placeKo": "팔 위쪽"},
  {"id": "custom-082", "cat": "floral", "w": 1501, "h": 2000, "en": "full arm thorn vine sleeve, black ink", "ko": "팔 전체 가시 넝쿨 슬리브, 블랙 잉크", "placeEn": "Full arm", "placeKo": "팔 전체"},
  {"id": "custom-083", "cat": "wave", "w": 1501, "h": 2000, "en": "knee tattoo, matching pair, wave and eye motif in teal", "ko": "무릎 타투, 대칭 한 쌍, 파도와 눈 모티프, 청록색", "placeEn": "Knee", "placeKo": "무릎"},
  {"id": "custom-084", "cat": "more", "w": 1602, "h": 2000, "en": "forearm abstract flame design, blue and black", "ko": "팔뚝 추상 불꽃 디자인, 파란색과 검정색", "placeEn": "Forearm", "placeKo": "팔뚝"},
  {"id": "custom-085", "cat": "more", "w": 1501, "h": 2000, "en": "upper arm deer tattoo, blue watercolor style", "ko": "팔뚝 위쪽 사슴 타투, 파란색 수채화 스타일", "placeEn": "Upper arm", "placeKo": "팔 위쪽"},
  {"id": "custom-086", "cat": "dragon", "w": 1602, "h": 2000, "en": "forearm dragon tattoo, grey ink with flower accent", "ko": "팔뚝 용 타투, 회색 잉크와 꽃 장식", "placeEn": "Forearm", "placeKo": "팔뚝"},
  {"id": "custom-087", "cat": "dragon", "w": 1501, "h": 2000, "en": "full arm dragon and snake sleeve, black and grey", "ko": "팔 전체 용과 뱀 슬리브, 흑회색", "placeEn": "Full arm", "placeKo": "팔 전체"},
  {"id": "custom-088", "cat": "wave", "w": 1602, "h": 2000, "en": "shoulder wave design, blue ink", "ko": "어깨 파도 디자인, 파란색 잉크", "placeEn": "Shoulder", "placeKo": "어깨"},
  {"id": "custom-089", "cat": "more", "w": 1600, "h": 2131, "en": "full arm abstract ornamental sleeve, pale blue", "ko": "팔 전체 추상 장식 슬리브, 연한 파란색", "placeEn": "Full arm", "placeKo": "팔 전체"},
  {"id": "custom-090", "cat": "more", "w": 1600, "h": 1997, "en": "forearm trident tattoo, blue ink", "ko": "팔뚝 삼지창 타투, 파란색 잉크", "placeEn": "Forearm", "placeKo": "팔뚝"},
  {"id": "custom-091", "cat": "more", "w": 1600, "h": 2131, "en": "upper arm cartoon devil tattoo, red and color", "ko": "팔뚝 위쪽 만화 악마 타투, 빨간색과 컬러", "placeEn": "Upper arm", "placeKo": "팔 위쪽"},
  {"id": "custom-092", "cat": "more", "w": 1600, "h": 1997, "en": "forearm hooded figure tattoo in heart frame, blue ink", "ko": "팔뚝 로브 입은 인물 타투, 하트 프레임, 파란색 잉크", "placeEn": "Forearm", "placeKo": "팔뚝"},
  {"id": "custom-093", "cat": "floral", "w": 1600, "h": 2400, "en": "knee flower tattoo with cloud accents, blue and gold", "ko": "무릎 꽃 타투와 구름 장식, 파란색과 금색", "placeEn": "Knee", "placeKo": "무릎"},
  {"id": "custom-094", "cat": "more", "w": 1600, "h": 2400, "en": "jawline ornamental tattoo, blue ink", "ko": "턱선 장식 타투, 파란색 잉크", "placeEn": "Neck & face", "placeKo": "목·얼굴"},
  {"id": "custom-095", "cat": "dragon", "w": 1600, "h": 2131, "en": "shoulder dragon tattoo, blue and white, wings spread", "ko": "어깨 용 타투, 파란색과 흰색, 날개 펼친 모습", "placeEn": "Shoulder", "placeKo": "어깨"},
  {"id": "custom-096", "cat": "floral", "w": 1600, "h": 2000, "en": "side and arm floral vine tattoo, blue ink", "ko": "옆구리와 팔 꽃 넝쿨 타투, 파란색 잉크", "placeEn": "Ribs", "placeKo": "옆구리"},
  {"id": "custom-097", "cat": "floral", "w": 1600, "h": 2000, "en": "upper arm spider lily tattoo, blue and orange", "ko": "팔뚝 위쪽 상사화 타투, 파란색과 주황색", "placeEn": "Upper arm", "placeKo": "팔 위쪽"},
  {"id": "custom-098", "cat": "more", "w": 1600, "h": 2131, "en": "upper arm reaper figure tattoo with roses, blue and gold", "ko": "팔뚝 위쪽 저승사자 캐릭터 타투와 장미, 파란색과 금색", "placeEn": "Upper arm", "placeKo": "팔 위쪽"},
  {"id": "custom-099", "cat": "wave", "w": 1600, "h": 998, "en": "shoulder swimmer tattoo, blue linework with waves", "ko": "어깨 수영하는 사람 타투, 파란색 라인워크와 파도", "placeEn": "Shoulder", "placeKo": "어깨"},
  {"id": "custom-100", "cat": "snake", "w": 1600, "h": 1997, "en": "forearm snake tattoo, blue ink, wrapping to hand", "ko": "팔뚝 뱀 타투, 파란색 잉크, 손까지 이어짐", "placeEn": "Forearm", "placeKo": "팔뚝"},
  {"id": "custom-101", "cat": "more", "w": 1600, "h": 2131, "en": "upper chest ornamental design, blue ink", "ko": "가슴 위쪽 장식 디자인, 파란색 잉크", "placeEn": "Chest", "placeKo": "가슴"},
  {"id": "custom-102", "cat": "dragon", "w": 1600, "h": 2131, "en": "ribs dragon tattoo, red and blue two-tone", "ko": "옆구리 용 타투, 빨간색과 파란색 투톤", "placeEn": "Ribs", "placeKo": "옆구리"},
  {"id": "custom-103", "cat": "dragon", "w": 1600, "h": 2000, "en": "thigh dragon tattoo, black ink", "ko": "허벅지 용 타투, 블랙 잉크", "placeEn": "Thigh", "placeKo": "허벅지"},
  {"id": "custom-104", "cat": "dragon", "w": 1600, "h": 2131, "en": "both arms dragon sleeves, blue and red", "ko": "양팔 용 슬리브, 파란색과 빨간색", "placeEn": "Full arm", "placeKo": "팔 전체"},
  {"id": "custom-105", "cat": "more", "w": 1600, "h": 2000, "en": "forearm cartoon sea creature tattoo, blue ink", "ko": "팔뚝 만화 바다생물 타투, 파란색 잉크", "placeEn": "Forearm", "placeKo": "팔뚝"},
  {"id": "custom-106", "cat": "more", "w": 1600, "h": 1997, "en": "upper arm tattoo collection, butterfly and fan", "ko": "팔뚝 위쪽 나비와 부채 모음 타투", "placeEn": "Upper arm", "placeKo": "팔 위쪽"},
  {"id": "custom-107", "cat": "dragon", "w": 1600, "h": 2000, "en": "upper arm dragon tattoo, blue and gold, coiled design", "ko": "팔뚝 위쪽 용 타투, 파란색과 금색, 똬리 튼 디자인", "placeEn": "Upper arm", "placeKo": "팔 위쪽"},
  {"id": "custom-108", "cat": "wave", "w": 1600, "h": 1998, "en": "forearm wave pattern tattoo, blue ink, wrist to forearm", "ko": "팔뚝 파도 패턴 타투, 파란색 잉크, 손목부터 팔뚝까지", "placeEn": "Forearm", "placeKo": "팔뚝"},
  {"id": "flash-01", "cat": "more", "w": 1400, "h": 1750, "en": "Flash", "ko": "", "placeEn": "", "placeKo": ""},
];
